### ISSUE TITLE
Restart problems

### ISSUE THREAD

**Issue by fantinialex** [opf/openproject-docker-compose#100]
When I create containers the first time, no problem. However, if I switch off all the containers and try to restart them with the previously stored data, everything starts but the web server does not respond to requests and then goes into timeout.

For the sake of completeness, I quote the only customisation file below.

``` yml
services:
  proxy:
    ports: !reset []
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.openproject.rule=Host(`openproject.example.com`)"

networks:
  traefik:
    external: true
```
