### ISSUE TITLE
Issue getting the Docker Compose install to work using the Synology DSM Container Manager

### ISSUE THREAD

**Issue by awa5114** [opf/openproject-docker-compose#108]
I'm trying to start an OpenProject compose application inside the Virtual DSM for testing purposes.  Here is the compose file for the Virtual DSM:

```yml
services:
  dsm:
    container_name: dsm
    image: vdsm/virtual-dsm
    environment:
      DISK_SIZE: "50G"
      RAM_SIZE: "2G"
      CPU_CORES: "2"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 5000:5000 # Synology UI
      - 8080:8080 # openproject
      - 22:22 # SSH
    volumes:
      - C:/Users/amine/Desktop/TEMP/dsm-docker/v722/storage:/storage
    restart: always
    stop_grace_period: 2m
```

 Once the Virtual DSM is successfully created, I go to `localhost:5000` on my browser and do the following:

- Install Container Manager
- Install and run Git Server

Using SSH, I navigate to `/volume1/docker`, and run the commands specified by the OpenProject docker compose install [page](https://www.openproject.org/docs/installation-and-operations/installation/docker-compose/#quick-start), namely

```
ssh@localhost> git clone https://github.com/opf/openproject-deploy --depth=1 --branch=stable/15 openproject
ssh@localhost> cp .env.example .env
```

I then launch the OpenProject compose application using the Container Manager.

It attempts to start up the application, but after a while, everything hangs, and I am no longer able to do any of the following:
- navigate to  the Synology UI from my browser (`localhost:5000`)
- SSH into the virtual DSM

Also, the OpenProject app is not up and running on `localhost:8080`. This is what the terminal on the VDSM shows before everything just freezes:

![Image](https://github.com/user-attachments/assets/f48f65bd-70d8-4da5-9e79-423b11659cf5)

Has anyone actually tested the Synology install at some point? If so what am I doing wrong here?
