### ISSUE TITLE
stable/16: Wrong pgsql version in docker-compose.yml

### ISSUE THREAD

**Issue by Kurapikov** [opf/openproject-docker-compose#113]
It should be 16 rather than 13.

BR.

**Comment by davemc50** [comment]
This is still an issue, and a trivial fix, how come such a straightforward issue sits open for six months?

**Comment by Tofandel** [comment]
It should even be 17

**Comment by nWacky** [comment]
For existing installations, Postgres data needs to be migrated before the version can be changed from 13 to 16.
https://www.openproject.org/docs/installation-and-operations/misc/migration-to-postgresql17/

Probably that's why the Postgres version in docker compose is old.

It would be nice to have a recent recommended Postgres version in docker compose by the default, though

**Comment by area51tazz** [comment]
Can we just change it to 17 for new installations? Other than the migration commands, I can't remember anything special about updating the docker compose file before pulling it.

**Comment by Tofandel** [comment]
You can with a `docker-compose.override.yml` file, if you already migrated your data to postgres 17 or for a new installation

```yml
services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: openproject
  # If you don't need the nginx reverse proxy
  proxy:
    profiles:
      - donotstart
```

This file is gitignored, so it will survive a git pull. This is the proper way to make customisations to the docker compose file
