### ISSUE TITLE
docker-compose needs update for HTTPS

### ISSUE THREAD

**Issue by torwag** [opf/openproject-docker-compose#38]
As HTTPS usage is now set true by default, it requires the set it to false for the provided docker-compose file. 
I did this and it seems to work, could provide a PR, but as I am not very deep into the project maybe a dev would like to do it in they way they want it.

**Comment by ainsofs** [comment]
Adding the following to the docker-compose.yml file fixed it for me

```
    OPENPROJECT_HTTPS: "false"
    OPENPROJECT_HOST__NAME: "localhost:8080"
```

It should go under the x-op-app: &app e.g.

```
version: "3.7"

...

x-op-app: &app
  environment:
    OPENPROJECT_HTTPS: "false"
    OPENPROJECT_HOST__NAME: "localhost:8080"
```
