### ISSUE TITLE
Error while docker compose up

### ISSUE THREAD

**Issue by sreenathmurali** [opf/openproject-docker-compose#42]
Hi,

Getting following error with docker-compose up

```
proxy_1     | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.31.0.3. Set the 'ServerName' directive globally to suppress this message
seeder_1    | /app/config/constants/settings/definition.rb:295:in `find_env_var_override': Using unprefixed environment variables is deprecated. Please use OPENPROJECT_ATTACHMENTS_STORAGE_PATH instead of ATTACHMENTS_STORAGE_PATH (StructuredWarnings::StandardWarning)
seeder_1    | /app/config/constants/settings/definition.rb:295:in `find_env_var_override': Using unprefixed environment variables is deprecated. Please use OPENPROJECT_RAILS_CACHE_STORE instead of RAILS_CACHE_STORE (StructuredWarnings::StandardWarning)
worker_1    | /app/config/constants/settings/definition.rb:295:in `find_env_var_override': Using unprefixed environment variables is deprecated. Please use OPENPROJECT_ATTACHMENTS_STORAGE_PATH instead of ATTACHMENTS_STORAGE_PATH (StructuredWarnings::StandardWarning)
worker_1    | /app/config/constants/settings/definition.rb:295:in `find_env_var_override': Using unprefixed environment variables is deprecated. Please use OPENPROJECT_RAILS_CACHE_STORE instead of RAILS_CACHE_STORE (StructuredWarnings::StandardWarning)
worker_1    | /app/lib/tasks/environment.rake:32:in `block (2 levels) in <top (required)>': Forcefully loading the application. Use :environment to avoid eager loading. (StructuredWarnings::StandardWarning)
web_1       | /app/config/constants/settings/definition.rb:295:in `find_env_var_override': Using unprefixed environment variables is deprecated. Please use OPENPROJECT_ATTACHMENTS_STORAGE_PATH instead of ATTACHMENTS_STORAGE_PATH (StructuredWarnings::StandardWarning)
web_1       | /app/config/constants/settings/definition.rb:295:in `find_env_var_override': Using unprefixed environment variables is deprecated. Please use OPENPROJECT_RAILS_CACHE_STORE instead of RAILS_CACHE_STORE (StructuredWarnings::StandardWarning)
web_1       | => Booting Puma
web_1       | => Rails 7.0.3.1 application starting in production
web_1       | => Run `bin/rails server --help` for more startup options
autoheal_1  | 21-09-2022 06:40:54 Container /compose_web_1 (777aa74f41ac) found to be unhealthy - Restarting container now with 10s timeout
web_1       | Exiting
compose_web_1 exited with code 1..
```

Any solution ?

**Comment by b12f** [comment]
I don't see any error, it seems like the container is too slow to start and then gets restarted too early because of a failing health check? @machisuji what do you think?

**Comment by dev-clavis** [comment]
Had the same problem.
Therefore I increased the healthcheck times (interval and timeout) in the docker-compose.yml
```
 healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080${OPENPROJECT_RAILS__RELATIVE__URL__ROOT:-}/health_checks/default"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
```
Because I didn't setup an SSL certificate I added
```
x-op-app: &app
  <<: [*image, *restart_policy]
  environment:
    OPENPROJECT_HTTPS: "false"
    OPENPROJECT_HSTS: "false"
```

OPENPROJECT_HTTPS, OPENPROJECT_HSTS to the env. vars.
