### ISSUE TITLE
Autoheal continuously restarting openproject

### ISSUE THREAD

**Issue by southeasterntech** [opf/openproject-docker-compose#64]
Is there a way to actually stop this container?  I'm trying to do an update, but I can't because I believe I can't disable the autoheal functionality.

**Comment by tbaden** [comment]
what helped me was to increase the `timeout` and `start_period` parameter in the healthcheck for the time of the upgrade process
```
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080${OPENPROJECT_RAILS__RELATIVE__URL__ROOT:-}/health_checks/default"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
      ```
